language: node_js
node_js:
- v5
branches:
  only: premaster
before_script:
- git config --global user.email "email@denysdovhan.com"
- git config --global user.name "Travis Builder"
- git remote rm origin
- git remote add origin https://denysdovhan:${GH_TOKEN}@github.com/denysdovhan/denysdovhan.github.io.git
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy || npm run build'
env:
  global:
    secure: Rj8N5tJ/sNOEHZ42I5JEKdzO0+gYowMTNHiNshwzg+h2z24+hRydJx1WZcYt8l3tae+fvr5uYJS4XIUlOZsiBvTJneOsiJFuakXUOpc+OebAXXTHKQPwTrGXDgZ/DmQSOFuautdBAvV0/s8E813TTywYjpljk11+VVnsRRv7neUOumLqkh+5TwpmIvnJLTboqxUgMl++Tl7Oc7dd7KtHVbMNhy5oRDCmwMpILSUSsX/l+1wCwrI2qbGHPRK+mLiK0ao0PxBTrCVQP/OhcANE0zmxxq/K8REMikd/Lx20EAXbA1bwvGt664ML5yN0PDEfL2ZhLY9wu55j25DaqBq9gf3SVHYzUZcCYWj/JQ9lUH9EzkBx3X9akrDoJQ8hVs5wxXL7O6/s0wSXsJ1zJqKD6PQlSQa7F2XxmueEjHSn1iA9p/rloow64NJgbOviSRvshpXyv/qMu+i3vwtyt4PPITeEyYT0ocrzZ3Z3Z3wnjoawCSda5dQvPxsgeBxTtqvi3HS7BpEL3QJDYqmjbNvoHRtYZofCvvWWHnjOxxpgzCZGgHkxzx2AGcyEPxaYacs9IXpI6tMLFS2ZsViFmQ5NwSo7CxDORSBq9CY5lZIRwwr4/BL1FFpvf0IDvoX1AZREgO8FB/6Wr8Hz/d/73D8+QvRjJH/f4K4GnnPyocbjMFA=
